name: rollmint-wordle
version: '3.8'
services:
  celestia-lc:
    image: celestia-node
    volumes:
      - ${KEY_PATH}/celestia-lc/:/root/${NODE_STORE}/keys:ro
      - ${PWD}/scripts/celestia/:/scripts:ro
    ports:
      - 26659:26659
    env_file:
      - ${PWD}/.env.celestia-lc
    command: /bin/sh -c '/scripts/init.sh && /scripts/start.sh'
  wordle:
    image: wordle-rollmint
    volumes:
      - ${KEY_PATH}/wordle/:/keys:ro
      - ${PWD}/scripts/wordle/:/scripts/:ro
    env_file:
      - ${PWD}/.env.wordle
    command: /bin/sh -c '/scripts/init.sh && /scripts/genesis.sh && /scripts/start.sh'

