name: rollmint-wordle
version: '3.8'
services:
  celestia-lc:
    image: celestia-node
    volumes:
      - ${KEY_PATH}/celestia-lc/:${NODE_STORE}/keys:ro
      - ${PWD}/scripts/celestia/:/scripts:ro
    ports:
      - 26657:26657
      - 26659:26659
    env_file:
      - ${PWD}/celestia-lc.env
    command: /bin/sh -c '/scripts/init.sh && /scripts/start.sh'
  wordle:
    image: wordle-rollmint
    volumes:
      - ${KEY_PATH}/wordle/:/keys:ro
      - ${PWD}/scripts/wordle/:/scripts/:ro
    env_file:
      - ${PWD}/wordle.env
    ports:
      - 26559:26559
    command: /bin/sh -c '/scripts/init.sh && /scripts/genesis.sh && /scripts/start.sh'
