version: '3.8'
services:
  celestia-lc:
    image: celestia-node:local
    volumes:
      - ${KEY_PATH}/celestia-lc:/root/${CELESTIA_LC_NODE_STORE}/keys
      - ${PWD}/scripts/celestia:/scripts
    ports:
      - 26659:26659
    command: /bin/sh -c "/scripts/init.sh && /scripts/start.sh"
  wordle:
    image: wordle-rollmint
    volumes:
      - ${KEY_PATH}/wordle:/keys
      - ${PWD}/scripts/wordle:/scripts/
    command: /bin/sh -c "/scripts/init.sh && /scripts/genesis.sh && /scripts/run.sh"
